#!/bin/bash
#BSUB -J extend
#BSUB -q 38
#BSUB -n 64
#BSUB -W 04:00
#BSUB -R "span[hosts=1]"
#BSUB -R "rusage[mem=2000]"
#BSUB -o logs/%J.out
#BSUB -e logs/%J.err

echo "Running on $(hostname)"
echo "Using $LSB_DJOB_NUMPROC cores"

module load python/anaconda3/2022.10
eval "$(conda shell.bash hook)"
conda activate trade_env

cd ~/TRADE

python scripts/data_processing/data_extender.py \
--save_path trade/Data/Original_space \
--column_name smiles
